In [5]:
import numpy as np

In [6]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,0]])
msuma = m1 + m2 
print(f"la suma de las matrices es {msuma}")

la suma de las matrices es [[ 6  8]
 [10  4]]


In [7]:
#generar un array con valores espaciados 
arreglo = np.linspace(0,9,10)
print(f"El arreglo es {arreglo}")

El arreglo es [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [8]:
# operaciones estadisticas 
arreglo = np.array([3,6,9,12,15])
print(f"El arreglo dado es {arreglo}, la suma es {np.sum(arreglo)}, la media es {np.mean(arreglo)}, el maximo es {np.max(arreglo)} y el minimo es {np.min(arreglo)}")

El arreglo dado es [ 3  6  9 12 15], la suma es 45, la media es 9.0, el maximo es 15 y el minimo es 3


### Numpy en la ciencia de datos 

In [9]:
# generar 1000 datos aleatorios entre cero y uno
datos_aleatorios = np.random.rand(1000)
print(f"imprimimos los primeros 10 {datos_aleatorios[:10]}")

imprimimos los primeros 10 [0.06161677 0.55719342 0.30084704 0.6070332  0.2889631  0.57770607
 0.93761848 0.37757836 0.42497841 0.26105471]


In [10]:
# calcular estadisticas sobre estos datos 
datos = np.array([22,18,25,30,28,24,20,19,22])
media = np.mean(datos)
mediana = np.median(datos)
des_estandar = np.std(datos)
print(f" meida {media}\n mediana {mediana}\n desviación estandar {des_estandar}")

 meida 23.11111111111111
 mediana 22.0
 desviación estandar 3.813556067051225


In [11]:
# indessacion y seleccion de datos 
datos = np.array([12, 8,15,10,6,18,14,9,11])
umbral = 10
datos_seleccionados = datos[datos > umbral]
print(f" Los datos son {datos}\n el umbral escojido fue {umbral}\n datos seleccionados {datos_seleccionados}")

 Los datos son [12  8 15 10  6 18 14  9 11]
 el umbral escojido fue 10
 datos seleccionados [12 15 18 14 11]


In [13]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_transpuesta = matriz.T
matriz_producto = np.dot(matriz,matriz)
print(f"La matriz original es\n {matriz} \n la matriz transpuesta es\n {matriz_transpuesta}\n y el producto de la matriz es\n {matriz_producto}")

La matriz original es
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 la matriz transpuesta es
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
 y el producto de la matriz es
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
arreglo_unidimensional = np.arange(10)
matriz_reshaped = arreglo_unidimensional.reshape(2,5)
matriz44 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
matriz_concat = np.concatenate((matriz_reshaped,matriz44), axis = 0)
#  0 significa a lo largo de la columna 
print(f"Arreglo unidimensional\n {arreglo_unidimensional}\n matriz rechape\n {matriz_reshaped}\n Matriz concatenada\n {matriz_concat}")

Arreglo unidimensional
 [0 1 2 3 4 5 6 7 8 9]
 matriz rechape
 [[0 1 2 3 4]
 [5 6 7 8 9]]
 Matriz concatenada
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [11 12 13 14 15]
 [16 17 18 19 20]]
