In [2]:
import numpy as np

In [5]:
l :list = [1,2,3,4,5,6]
array = np.array(l)
print(l,type(array),array)

[1, 2, 3, 4, 5, 6] <class 'numpy.ndarray'> [1 2 3 4 5 6]


In [6]:
l2 :list = [[1,2,3],[2,5,6],[4,4,5]]
array2 = np.array(l2)


In [7]:
array2

array([[1, 2, 3],
       [2, 5, 6],
       [4, 4, 5]])

In [23]:
array = np.arange(6)
array3 = np.arange(2,15,2)
print(array, array3)

[0 1 2 3 4 5] [ 2  4  6  8 10 12 14]


In [15]:
m0 = np.zeros((4,5))
m1 = np.ones((4,5))
mi = np.eye(4)
mran =np.random.rand(4)
mrna2 = np.random.randint(1,51,50)

print(m0,m1,mi,mran,mrna2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] [0.00920387 0.47274993 0.68522784 0.0674392 ] [14 29 18 42 31 23 13 24 29 26 13 40 31 14 15 20 38 13 50 45 39 47 16 32
  2 25 29  1 15 45 46 16 28  7 48 28 14 41 26 28 29 25 27 36 39 34 14 12
 25 22]


In [18]:
mrna2 = np.random.randint(1,201,30)
print(mrna2)

[ 82  91  26 165 114  25   5 158 127  95 125   6 189  33  14 153  22  59
 132  22  54  72 127   5  36 135 150  61  43 105]


In [13]:
array = np.random.randint(1,201,30)
matriz = array.reshape(5,6)
print(m)

[[187  35 150 108 120 197]
 [138 111 200  64  63 153]
 [194  18   5  66   8  39]
 [ 58  73  37  28   6  67]
 [ 26 103  19  54 174 154]]


In [9]:
array = np.random.randint(1,901,200)
print(array)
#para saber el numero maximo
maximo = array.max()
print(f"El valor maximo es {maximo}")
print(array.argmax())


minimo = array.min()
print(f"El minimo es {minimo}")
print(array.argmin())


[804 700 535 347 281 117 739 369 675 577 715 881 324 757 196 279 750  16
 733 537 294 787 641 305 759 423 531 520 825 753  32 476 541 173 134 346
 427 843 369 836  77 741 775 611  60 195 193 527 851 283 316 725 625 333
 633 512 246 655 275 572 450   8 435 668 770 836 684 307 511  44 503 319
 851 363 472  63 596 630 612 260 468 266 530 402 699 839 833 278 435 228
  55  95 688 765 230 355  47 219 485 759 788   5 502 593 302 352 326  14
 106 183 333 695 144 360 343 784 568 288 638 654 808 659 511  60 852 116
 179 858  83 507 223 500 443 432 686 253 812 533 109 290  84 713  14 550
 581 119 536 298 290 854 541 419 329 286 170 515 127 551 877 598 482 610
 505 655 390 690 209 495 554 807 834 152 419 668 487 668 598 581 761 123
 549 472 749 304 804 122 806 666 214 481 620 799 326 858 232 787 890 363
 184 482]
El valor maximo es 890
196
El minimo es 5
101


In [10]:
array = np.arange(1,11)  #genera del cero al 10
print(array)
print(array[2])
print(array[5:])
print(array[:6])


[ 1  2  3  4  5  6  7  8  9 10]
3
[ 6  7  8  9 10]
[1 2 3 4 5 6]


In [12]:
array = np.arange(1,11)
array2 = array.copy()
print(array)
print(array2)
array2[4] = 100
print(10**100)
print(array)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4 100   6   7   8   9  10]


In [22]:
array = np.random.randint(1,201,30)
matriz = array.reshape(5,6)
print(matriz)
print(matriz[0])  #primrea linea de la matriz
print(matriz[:2])  #sini seleccion de filas, selecciona las dos primeras filas 
print(matriz[1][2])



[[112 118   6 120 128  75]
 [174  34 166  71  10 151]
 [ 92 117 160 169 176 104]
 [ 39  13 147  50  59 159]
 [196  45  30  69  70  29]]
[112 118   6 120 128  75]
[[112 118   6 120 128  75]
 [174  34 166  71  10 151]]
166


In [23]:
print(matriz[:, :1]) #antes de la coma se selecciona todo lo que esta antes

[[112]
 [174]
 [ 92]
 [ 39]
 [196]]


In [31]:
array = np.random.randint(1,201,30)
matriz = array.reshape(5,6)
print(matriz)
print("*"*50)
# en numpy la suma es directa cuando es escalar + matriz
print(matriz+10)
print("*"*50)
print(matriz+matriz)
print("*"*50)
print(matriz*10)



[[ 61 158 139 101 185 153]
 [195  37 180 110 105  95]
 [200 195 141 112 186  37]
 [ 70 176 134  31  97 143]
 [ 92  20  37 108  30 103]]
**************************************************
[[ 71 168 149 111 195 163]
 [205  47 190 120 115 105]
 [210 205 151 122 196  47]
 [ 80 186 144  41 107 153]
 [102  30  47 118  40 113]]
**************************************************
[[122 316 278 202 370 306]
 [390  74 360 220 210 190]
 [400 390 282 224 372  74]
 [140 352 268  62 194 286]
 [184  40  74 216  60 206]]
**************************************************
[[ 610 1580 1390 1010 1850 1530]
 [1950  370 1800 1100 1050  950]
 [2000 1950 1410 1120 1860  370]
 [ 700 1760 1340  310  970 1430]
 [ 920  200  370 1080  300 1030]]


In [36]:
array = np.random.randint(1,201,30)
matriz = array.reshape(5,6) 
print(matriz, np.max(matriz))


[[ 60  13  51 198  25 152]
 [195 118 151 114  85 131]
 [ 34 100  21 102   5 198]
 [ 93   1  26  46   8 199]
 [ 72  27  86  44 128 115]] 199


In [38]:
array = np.random.randint(1,201,30)
matriz = array.reshape(5,6)
condicion = matriz > 100
print(condicion)

[[False  True  True  True False False]
 [False False  True False  True False]
 [ True False  True False False  True]
 [False False  True  True  True False]
 [False False False  True  True False]]


In [40]:
condiciones = (matriz % 2 == 0)
print(condiciones)
print(matriz[condiciones])

[[False  True False  True  True  True]
 [False  True False  True False  True]
 [False False  True  True False  True]
 [False  True  True  True  True  True]
 [ True False False  True  True  True]]
[112 124  34  32  80  32  88 118  78 110  60 170 128 138  24  16 188 174
   6]


In [45]:
lista = np.arange(5,41)
# se tiene una dimencion cpn varios indices
lista = lista.reshape(3,12)
print(lista, "\n", lista[2,4])


[[ 5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36 37 38 39 40]] 
 33


In [46]:
array_primitiva = np.random.randint(1,50,6)
print(f"la combinación de la lotería es {array_primitiva}")

la combinación de la lotería es [49 43 18  7 40 18]
